kind: pipeline
name: default
type: docker

steps:
    -   name: get
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go get
    -   name: vet
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go vet
        depends_on: [ get ]
    -   name: tests
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go test ./... -tags ""
            - go test ./... -tags "scrape record"
        depends_on: [ get ]
    -   name: build
        image: golang:1.11
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - go version
            - go build -tags ""
            - go build -tags "scrape record"
        depends_on: [ get ]
    -   name: linter
        image: golangci/golangci-lint:latest
        environment:
            GO111MODULE: on
            GOPATH: /drone/src/.go
        commands:
            - golangci-lint run --color always --build-tags ""
            - golangci-lint run --color always --build-tags "scrape record"
        depends_on: [ build ]
