name: compliance

on:
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

jobs:
    linter:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Set up Go
                uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
                with:
                    go-version-file: ./go.mod
            -   name: Run linter
                uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8